//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Configurator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplexLink
    {
        public int ComplexDataId { get; set; }
        public int LookupId { get; set; }
        public bool Available { get; set; }
    
        public virtual ComplexLookup ComplexLookup { get; set; }
        public virtual Lookup Lookup { get; set; }
    }
}
