//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Configurator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public Config()
        {
            this.ConfigDatas = new HashSet<ConfigData>();
        }
    
        public string ConfigID { get; set; }
        public string ConfigData { get; set; }
        public int Sequence { get; set; }
    
        public virtual ICollection<ConfigData> ConfigDatas { get; set; }
        public virtual ConfigID ConfigID1 { get; set; }
    }
}
