//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Configurator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConfiguratorEntities : DbContext
    {
        public ConfiguratorEntities()
            : base("name=ConfiguratorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Config> Configs { get; set; }
        public virtual DbSet<ConfigData> ConfigDatas { get; set; }
        public virtual DbSet<ConfigID> ConfigIDs { get; set; }
        public virtual DbSet<ConfigLookup1> ConfigLookup1 { get; set; }
        public virtual DbSet<ConfigLookup10> ConfigLookup10 { get; set; }
        public virtual DbSet<ConfigLookup2> ConfigLookup2 { get; set; }
        public virtual DbSet<ConfigLookup3> ConfigLookup3 { get; set; }
        public virtual DbSet<ConfigLookup4> ConfigLookup4 { get; set; }
        public virtual DbSet<ConfigLookup5> ConfigLookup5 { get; set; }
        public virtual DbSet<ConfigLookup6> ConfigLookup6 { get; set; }
        public virtual DbSet<ConfigLookup7> ConfigLookup7 { get; set; }
        public virtual DbSet<ConfigLookup8> ConfigLookup8 { get; set; }
        public virtual DbSet<ConfigLookup9> ConfigLookup9 { get; set; }
        public virtual DbSet<ConfigPricing> ConfigPricings { get; set; }
    }
}
