//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Configurator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigID
    {
        public ConfigID()
        {
            this.Configs = new HashSet<Config>();
        }
    
        public string ConfigID1 { get; set; }
    
        public virtual ICollection<Config> Configs { get; set; }
    }
}
