//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Configurator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigData
    {
        public string ConfigID { get; set; }
        public string ConfigData1 { get; set; }
        public int Sequence { get; set; }
        public string Data { get; set; }
        public Nullable<bool> Inactive { get; set; }
    
        public virtual Config Config { get; set; }
    }
}
