//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Configurator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConfiguratorEntities : DbContext
    {
        public ConfiguratorEntities()
            : base("name=ConfiguratorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConfigBuild> ConfigBuilds { get; set; }
        public virtual DbSet<ConfigOption1> ConfigOption1 { get; set; }
        public virtual DbSet<ConfigOption10> ConfigOption10 { get; set; }
        public virtual DbSet<ConfigOption2> ConfigOption2 { get; set; }
        public virtual DbSet<ConfigOption3> ConfigOption3 { get; set; }
        public virtual DbSet<ConfigOption4> ConfigOption4 { get; set; }
        public virtual DbSet<ConfigOption5> ConfigOption5 { get; set; }
        public virtual DbSet<ConfigOption6> ConfigOption6 { get; set; }
        public virtual DbSet<ConfigOption7> ConfigOption7 { get; set; }
        public virtual DbSet<ConfigOption8> ConfigOption8 { get; set; }
        public virtual DbSet<ConfigOption9> ConfigOption9 { get; set; }
        public virtual DbSet<ConfigPricing> ConfigPricings { get; set; }
        public virtual DbSet<ConfiguratorName> ConfiguratorNames { get; set; }
        public virtual DbSet<Structure> Structures { get; set; }
        public virtual DbSet<StructureSeq> StructureSeqs { get; set; }
        public virtual DbSet<Lookup> Lookups { get; set; }
        public virtual DbSet<ComplexLookup> ComplexLookups { get; set; }
        public virtual DbSet<ComplexStructure> ComplexStructures { get; set; }
    }
}
