//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Configurator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigOption
    {
        public int Id { get; set; }
        public string ConfigName { get; set; }
        public string ConfigData { get; set; }
        public string Key01 { get; set; }
        public string Key02 { get; set; }
        public string Key03 { get; set; }
        public string Key04 { get; set; }
        public string Key05 { get; set; }
        public string Key06 { get; set; }
        public string Key07 { get; set; }
        public string Key08 { get; set; }
        public string Key09 { get; set; }
        public string Key10 { get; set; }
        public string PartNum { get; set; }
        public bool InActive { get; set; }
    }
}
