//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Configurator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigPricing
    {
        public string ConfigID { get; set; }
        public string ConfigOption { get; set; }
        public decimal Price { get; set; }
        public decimal AltPrice { get; set; }
    }
}
