//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Configurator
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialCustomer
    {
        public SpecialCustomer()
        {
            this.SpecialConfigs = new HashSet<SpecialConfig>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SpecialConfig> SpecialConfigs { get; set; }
    }
}
