//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Configurator
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialData
    {
        public int Id { get; set; }
        public int SpecialConfigId { get; set; }
        public int SpecialDataTypeId { get; set; }
        public string Part { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> RelatedOpId { get; set; }
    
        public virtual SpecialConfig SpecialConfig { get; set; }
        public virtual SpecialDataType SpecialDataType { get; set; }
        public virtual SpecialRelatedOp SpecialRelatedOp { get; set; }
    }
}
