//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Configurator
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialRelatedOp
    {
        public SpecialRelatedOp()
        {
            this.SpecialDatas = new HashSet<SpecialData>();
        }
    
        public int Id { get; set; }
        public int RelatedOp { get; set; }
        public string Operation { get; set; }
    
        public virtual ICollection<SpecialData> SpecialDatas { get; set; }
    }
}
