//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Legacy.EntityModels.Legacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceHeader
    {
        public string CompanyId { get; set; }
        public string InvoiceNumber { get; set; }
        public string OrderType { get; set; }
        public string BatchNumber { get; set; }
        public string DropShipFlag { get; set; }
        public string CustomerNumber { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerAddress2 { get; set; }
        public string CustomerAddress3 { get; set; }
        public string ShipToCode { get; set; }
        public string CustomerOrderNumber { get; set; }
        public string ShipVia { get; set; }
        public string FOB { get; set; }
        public Nullable<System.DateTime> DateOrdered { get; set; }
        public string DateShipped { get; set; }
        public Nullable<System.DateTime> DateInvoiced { get; set; }
        public Nullable<int> TimesUpdated { get; set; }
        public string LastOrderNumber { get; set; }
        public string Salesman { get; set; }
        public string TermsCode { get; set; }
        public string CostPrice { get; set; }
        public string LiftOrderNumber { get; set; }
        public string PartsFlag { get; set; }
        public string DateRequired { get; set; }
        public string SerialNumber { get; set; }
        public string ShipViaCode { get; set; }
        public string Warranty { get; set; }
        public string InventoryStatus { get; set; }
        public string DateATSCurrent { get; set; }
        public string DateATSPrior { get; set; }
        public string DateATSOriginal { get; set; }
        public string Open136 { get; set; }
        public Nullable<double> GrossSales1 { get; set; }
        public Nullable<double> GrossSales2 { get; set; }
        public Nullable<double> GrossSales3 { get; set; }
        public Nullable<double> GrossSales4 { get; set; }
        public Nullable<double> GrossSalesOther { get; set; }
        public Nullable<double> CostOfSales { get; set; }
        public Nullable<double> MiscCharges { get; set; }
        public Nullable<double> TaxableTotal { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public Nullable<double> SalesTaxAmount { get; set; }
        public Nullable<double> FreightAmount { get; set; }
        public Nullable<double> InvoiceAmount { get; set; }
        public Nullable<double> CommissionBaseAmount { get; set; }
        public Nullable<double> SalesTax { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> Commission { get; set; }
        public string NumberShipLabels { get; set; }
        public string LiftModel { get; set; }
    }
}
