//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Legacy.EntityModels.Legacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEGACYSWO011H
    {
        public string Company { get; set; }
        public string WorkOrderNumber { get; set; }
        public string SpecialInstruction1 { get; set; }
        public string SerialNumber { get; set; }
        public string LiftOrderNumber { get; set; }
        public string CloseDate { get; set; }
        public string ATSDate1 { get; set; }
        public string ATSDate2 { get; set; }
        public string ATSDate3 { get; set; }
        public string JITRunDate { get; set; }
        public string XRayFlag { get; set; }
        public string PaintedFlag { get; set; }
        public string ScannedPullCodes { get; set; }
        public string GreenDotDate { get; set; }
        public string ChangeOrderCompleteDate { get; set; }
        public string TestInspectDate { get; set; }
        public string UpperBoomMilliampLeakage { get; set; }
        public string LowerBoomMilliampLeakage { get; set; }
        public string Category { get; set; }
        public string ZapperSerialNumber { get; set; }
        public string ZapTestDate { get; set; }
        public string SpecialInstructions2 { get; set; }
        public string SpecialInstructions3 { get; set; }
    }
}
