//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Legacy.EntityModels.Legacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiftCost
    {
        public int Id { get; set; }
        public string LiftNum { get; set; }
        public string OrderCompanyNum { get; set; }
        public string OrderNum { get; set; }
        public string CustCompanyNum { get; set; }
        public string Customer { get; set; }
        public Nullable<System.DateTime> LiftTestDate { get; set; }
        public string LiftModel { get; set; }
        public Nullable<decimal> SalesOrderTotal { get; set; }
        public Nullable<decimal> LiftMatlCostWTrkBdy { get; set; }
        public Nullable<decimal> LiftLaborCost { get; set; }
        public Nullable<decimal> TruckCost { get; set; }
        public Nullable<decimal> BodyCost { get; set; }
    }
}
