//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Legacy.EntityModels.Legacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseHistory_Mods
    {
        public string Company { get; set; }
        public string PartNumber { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public string SupplierNumber { get; set; }
        public string PO_Number { get; set; }
        public string PO_Line_Number { get; set; }
        public string ReceiptQty { get; set; }
        public string Qty { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string SupplierName { get; set; }
    }
}
