//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Legacy.EntityModels.Legacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedrillPartXRef
    {
        public string ReedrillPartNumber { get; set; }
        public string DrawingNumber { get; set; }
        public string AptCart { get; set; }
        public string DrawingSize { get; set; }
        public string DrawingRev { get; set; }
        public string DwgBOM { get; set; }
        public string CADdb { get; set; }
        public string CADSize { get; set; }
        public string CADRev { get; set; }
        public string CADbom { get; set; }
        public string LineDrawing { get; set; }
        public string LineDrawingSize { get; set; }
        public string LineDrawingRevision { get; set; }
        public string LineDrawingBOM { get; set; }
        public string Comments { get; set; }
    }
}
