//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Legacy.EntityModels.Legacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarrantyComponent
    {
        public int Id { get; set; }
        public string SerialNumber { get; set; }
        public string Name { get; set; }
        public string LineNumber { get; set; }
        public string ManufactorName { get; set; }
    }
}
