//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.DataPlates
{
    using System;
    using System.Collections.Generic;
    
    public partial class DielectricRating
    {
        public int SearchOrder { get; set; }
        public string Name { get; set; }
        public string SearchString { get; set; }
        public string Rating { get; set; }
        public string LineVoltage { get; set; }
    }
}
