//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.DataPlates
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiftData
    {
        public string Lift { get; set; }
        public Nullable<int> HydOilPSI { get; set; }
        public Nullable<int> HydOilKG { get; set; }
        public Nullable<bool> Insulated { get; set; }
        public string DesignVoltage { get; set; }
    }
}
