//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Support.EntityModels.TimeMfg
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketRequestor
    {
        public int EmployeeID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Division { get; set; }
        public string Title { get; set; }
        public string EmailName { get; set; }
        public string Extension { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
    }
}
