//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Support.EntityModels.TimeMfg
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketStatus
    {
        public TicketStatus()
        {
            this.TicketProjects = new HashSet<TicketProject>();
            this.TicketStatusHistories = new HashSet<TicketStatusHistory>();
        }
    
        public int StatusID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool isOpen { get; set; }
        public bool isActive { get; set; }
        public Nullable<bool> isSupRequest { get; set; }
        public Nullable<bool> isReadyToComplete { get; set; }
        public Nullable<bool> isReadyToCancel { get; set; }
    
        public virtual ICollection<TicketProject> TicketProjects { get; set; }
        public virtual ICollection<TicketStatusHistory> TicketStatusHistories { get; set; }
    }
}
