//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Support.EntityModels.TimeMfg
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketLink
    {
        public int Id { get; set; }
        public int SourceTicketId { get; set; }
        public int TargetTicketId { get; set; }
    
        public virtual TicketProject TicketProject { get; set; }
        public virtual TicketProject TicketProject1 { get; set; }
    }
}
