//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Invoicing.EntityModels.PcInvoice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chassis
    {
        public Chassis()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.OrderHeaders = new HashSet<OrderHeader>();
        }
    
        public int Id { get; set; }
        public int ModelYearId { get; set; }
        public int ChassisModelId { get; set; }
        public int TransmissionId { get; set; }
        public int CALookupId { get; set; }
        public int GVWLookupId { get; set; }
        public bool Inactive { get; set; }
        public string FullName { get; set; }
    
        public virtual CALookup CALookup { get; set; }
        public virtual ChassisModel ChassisModel { get; set; }
        public virtual GVWLookup GVWLookup { get; set; }
        public virtual ModelYearLookup ModelYearLookup { get; set; }
        public virtual Transmission Transmission { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<OrderHeader> OrderHeaders { get; set; }
    }
}
