//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Invoicing.EntityModels.PcInvoice
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceHistory
    {
        public int Id { get; set; }
        public int OrderHeaderId { get; set; }
        public int OrderDetaiIId { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string Email { get; set; }
        public string InvoiceNumber { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public string FileName { get; set; }
    
        public virtual OrderDetail OrderDetail { get; set; }
        public virtual OrderHeader OrderHeader { get; set; }
    }
}
