//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Invoicing.EntityModels.PcInvoice
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHeader
    {
        public OrderHeader()
        {
            this.InvoiceHistories = new HashSet<InvoiceHistory>();
            this.MiscInstalls = new HashSet<MiscInstall>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.OrderDetailsOrderOptionsLinks = new HashSet<OrderDetailsOrderOptionsLink>();
            this.OrderOptions = new HashSet<OrderOption>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public string PurchaseOrder { get; set; }
        public string DropShipCode { get; set; }
        public string PreliminaryInvoiceMessage { get; set; }
        public string PreliminaryInvoiceEmail { get; set; }
        public string Notes { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool InActive { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> UpfitterId { get; set; }
        public Nullable<int> ChassisId { get; set; }
        public Nullable<int> ShipToId { get; set; }
        public string QuoteNum { get; set; }
        public Nullable<int> InvoiceNumberTemplateId { get; set; }
        public Nullable<int> OrderYear { get; set; }
        public Nullable<int> FoblookupId { get; set; }
        public string FobPlace { get; set; }
        public Nullable<int> TermsLookupId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Chassis Chassis { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual FobLookup FobLookup { get; set; }
        public virtual ICollection<InvoiceHistory> InvoiceHistories { get; set; }
        public virtual InvoiceNumberTemplate InvoiceNumberTemplate { get; set; }
        public virtual ICollection<MiscInstall> MiscInstalls { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<OrderDetailsOrderOptionsLink> OrderDetailsOrderOptionsLinks { get; set; }
        public virtual ShipTo ShipTo { get; set; }
        public virtual TermsLookup TermsLookup { get; set; }
        public virtual Upfitter Upfitter { get; set; }
        public virtual ICollection<OrderOption> OrderOptions { get; set; }
    }
}
