//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Invoicing.EntityModels.PcInvoice
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PCInvoiceEntities : DbContext
    {
        public PCInvoiceEntities()
            : base("name=PCInvoiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CALookup> CALookups { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Chassis> Chassis { get; set; }
        public virtual DbSet<ChassisMake> ChassisMakes { get; set; }
        public virtual DbSet<ChassisModel> ChassisModels { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<FobLookup> FobLookups { get; set; }
        public virtual DbSet<GVWLookup> GVWLookups { get; set; }
        public virtual DbSet<InvoiceHistory> InvoiceHistories { get; set; }
        public virtual DbSet<InvoiceNumberTemplate> InvoiceNumberTemplates { get; set; }
        public virtual DbSet<MiscChargeType> MiscChargeTypes { get; set; }
        public virtual DbSet<MiscInstall> MiscInstalls { get; set; }
        public virtual DbSet<ModelYearLookup> ModelYearLookups { get; set; }
        public virtual DbSet<NLog_Error> NLog_Error { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<OrderDetailsOrderOptionsLink> OrderDetailsOrderOptionsLinks { get; set; }
        public virtual DbSet<OrderHeader> OrderHeaders { get; set; }
        public virtual DbSet<OrderOption> OrderOptions { get; set; }
        public virtual DbSet<ShipTo> ShipToes { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<TaskQueue> TaskQueues { get; set; }
        public virtual DbSet<TermsLookup> TermsLookups { get; set; }
        public virtual DbSet<Transmission> Transmissions { get; set; }
        public virtual DbSet<Upfitter> Upfitters { get; set; }
    }
}
