//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Invoicing.EntityModels.PcInvoice
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskQueue
    {
        public int Id { get; set; }
        public string Submitter { get; set; }
        public string VehicleNumber { get; set; }
        public System.DateTime Created { get; set; }
        public string TaskType { get; set; }
        public int OrderDetailId { get; set; }
        public string OrderLines { get; set; }
        public string AdditionalMessage { get; set; }
        public bool InProcess { get; set; }
        public bool Cancelled { get; set; }
        public bool Completed { get; set; }
        public bool EmailSent { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string Result { get; set; }
        public string FileName { get; set; }
        public string Email { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
    }
}
