//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobAsmbl
    {
        public string Company { get; set; }
        public bool JobComplete { get; set; }
        public string JobNum { get; set; }
        public int AssemblySeq { get; set; }
        public string PartNum { get; set; }
        public string Description { get; set; }
        public string RevisionNum { get; set; }
        public decimal QtyPer { get; set; }
        public string IUM { get; set; }
        public decimal RequiredQty { get; set; }
        public decimal PullQty { get; set; }
        public string WarehouseCode { get; set; }
        public decimal MtlBurRate { get; set; }
        public decimal EstUnitCost { get; set; }
        public decimal EstMtlBurUnitCost { get; set; }
        public decimal OverRunQty { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public decimal StartHour { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public decimal DueHour { get; set; }
        public int Parent { get; set; }
        public int PriorPeer { get; set; }
        public int NextPeer { get; set; }
        public int Child { get; set; }
        public decimal TotalCost { get; set; }
        public decimal MtlBurCost { get; set; }
        public decimal IssuedQty { get; set; }
        public string DrawNum { get; set; }
        public bool IssuedComplete { get; set; }
        public string CommentText { get; set; }
        public bool InCopyList { get; set; }
        public int BomSequence { get; set; }
        public int BomLevel { get; set; }
        public Nullable<System.DateTime> WIStartDate { get; set; }
        public decimal WIStartHour { get; set; }
        public Nullable<System.DateTime> WIDueDate { get; set; }
        public decimal WIDueHour { get; set; }
        public decimal TLALaborCost { get; set; }
        public decimal TLABurdenCost { get; set; }
        public decimal TLAMaterialCost { get; set; }
        public decimal TLASubcontractCost { get; set; }
        public decimal TLAMtlBurCost { get; set; }
        public decimal TLASetupHours { get; set; }
        public decimal TLAProdHours { get; set; }
        public decimal TLELaborCost { get; set; }
        public decimal TLEBurdenCost { get; set; }
        public decimal TLEMaterialCost { get; set; }
        public decimal TLESubcontractCost { get; set; }
        public decimal TLEMtlBurCost { get; set; }
        public decimal TLESetupHours { get; set; }
        public decimal TLEProdHours { get; set; }
        public decimal LLALaborCost { get; set; }
        public decimal LLABurdenCost { get; set; }
        public decimal LLAMaterialCost { get; set; }
        public decimal LLASubcontractCost { get; set; }
        public decimal LLAMtlBurCost { get; set; }
        public decimal LLASetupHours { get; set; }
        public decimal LLAProdHours { get; set; }
        public decimal LLELaborCost { get; set; }
        public decimal LLEBurdenCost { get; set; }
        public decimal LLEMaterialCost { get; set; }
        public decimal LLESubcontractCost { get; set; }
        public decimal LLEMtlBurCost { get; set; }
        public decimal LLESetupHours { get; set; }
        public decimal LLEProdHours { get; set; }
        public int AutoRecOpr { get; set; }
        public int FinalOpr { get; set; }
        public string FindNum { get; set; }
        public decimal ReceivedToStock { get; set; }
        public string Plant { get; set; }
        public bool Direct { get; set; }
        public int RelatedOperation { get; set; }
        public decimal TLAMaterialLabCost { get; set; }
        public decimal TLAMaterialMtlCost { get; set; }
        public decimal TLAMaterialSubCost { get; set; }
        public decimal TLAMaterialBurCost { get; set; }
        public decimal LLAMaterialLabCost { get; set; }
        public decimal LLAMaterialMtlCost { get; set; }
        public decimal LLAMaterialSubCost { get; set; }
        public decimal LLAMaterialBurCost { get; set; }
        public decimal TotalMtlMtlCost { get; set; }
        public decimal TotalMtlLabCost { get; set; }
        public decimal TotalMtlSubCost { get; set; }
        public decimal TotalMtlBurCost { get; set; }
        public int CallNum { get; set; }
        public int CallLine { get; set; }
        public string RestoreFlag { get; set; }
        public string AnalysisCode { get; set; }
        public Nullable<System.DateTime> LastConfigDate { get; set; }
        public int LastConfigTime { get; set; }
        public string LastConfigUserID { get; set; }
        public decimal OrigRequiredQty { get; set; }
        public string UserMapData { get; set; }
        public bool WhseAllocFlag { get; set; }
        public decimal TLAMaterialMtlBurCost { get; set; }
        public decimal LLAMaterialMtlBurCost { get; set; }
        public decimal TLAMfgCompLabCost { get; set; }
        public decimal TLAMfgCompMtlCost { get; set; }
        public decimal TLAMfgCompSubCost { get; set; }
        public decimal TLAMfgCompBurCost { get; set; }
        public decimal TLAMfgCompMtlBurCost { get; set; }
        public decimal LLAMfgCompLabCost { get; set; }
        public decimal LLAMfgCompMtlCost { get; set; }
        public decimal LLAMfgCompSubCost { get; set; }
        public decimal LLAMfgCompBurCost { get; set; }
        public decimal LLAMfgCompMtlBurCost { get; set; }
        public decimal Weight { get; set; }
        public string WeightUOM { get; set; }
        public int OrigMtlSeq { get; set; }
        public string OrigRuleTag { get; set; }
        public bool ValRefDes { get; set; }
        public string BasePartNum { get; set; }
        public string BaseRevisionNum { get; set; }
        public decimal EstMtlUnitCost { get; set; }
        public decimal EstLbrUnitCost { get; set; }
        public decimal EstBurUnitCost { get; set; }
        public decimal EstSubUnitCost { get; set; }
        public bool PlanAsAsm { get; set; }
        public string PAARef { get; set; }
        public bool PAAFirm { get; set; }
        public decimal EstScrap { get; set; }
        public string EstScrapType { get; set; }
        public bool SmartStringProcessed { get; set; }
        public string SmartString { get; set; }
        public int ReqRefDes { get; set; }
        public bool ReassignSNAsm { get; set; }
        public decimal TLAODCCost { get; set; }
        public string AssemblyMatch { get; set; }
        public string JdfStatus { get; set; }
        public string PressDevice { get; set; }
        public string DigitalFileName { get; set; }
        public string PrepressJobName { get; set; }
        public string JdfPrepressAction { get; set; }
        public bool SendToPress { get; set; }
        public bool RemovedFromPlan { get; set; }
        public int SendToPressInitiator { get; set; }
        public int OperationType { get; set; }
        public bool SendToPrePress { get; set; }
        public int GroupSeq { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public string PartPlanInfo { get; set; }
        public string OrigStructTag { get; set; }
        public string ContractID { get; set; }
        public bool LinkToContract { get; set; }
        public bool PCLinkRemoved { get; set; }
    }
}
