//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysAgentSched
    {
        public string AgentID { get; set; }
        public int AgentSchedNum { get; set; }
        public string SchedDesc { get; set; }
        public string SchedType { get; set; }
        public Nullable<System.DateTime> NextRunOn { get; set; }
        public int Recurrences { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string MonthlyOption { get; set; }
        public int DayOfMonth { get; set; }
        public string WeekOfMonth { get; set; }
        public int DayOfWeek { get; set; }
        public int EveryNWeeks { get; set; }
        public Nullable<System.DateTime> LastRunOn { get; set; }
        public bool Mondays { get; set; }
        public bool Tuesdays { get; set; }
        public bool Wednesdays { get; set; }
        public bool Thursdays { get; set; }
        public bool Fridays { get; set; }
        public bool Saturdays { get; set; }
        public bool Sundays { get; set; }
        public bool Enabled { get; set; }
        public string AppSrvConnectionID { get; set; }
        public int IntervalTime { get; set; }
        public string SecCode { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
    }
}
