//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysAgentTask
    {
        public string AgentID { get; set; }
        public int AgentSchedNum { get; set; }
        public int AgentTaskNum { get; set; }
        public string TaskDesc { get; set; }
        public string TaskType { get; set; }
        public string RunProcedure { get; set; }
        public string RunMethod { get; set; }
        public Nullable<System.DateTime> SubmittedOn { get; set; }
        public string SubmitUser { get; set; }
        public string ParamMaintProgram { get; set; }
        public string Company { get; set; }
        public string TaskNote { get; set; }
        public string ProcessSetSystemCode { get; set; }
        public string ProcessID { get; set; }
        public int ProcessTaskNum { get; set; }
        public bool IsSystemTask { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
    }
}
