//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysTaskLog
    {
        public long SysTaskNum { get; set; }
        public int EntryNum { get; set; }
        public Nullable<System.DateTime> EnteredOn { get; set; }
        public bool IsError { get; set; }
        public string MsgText { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
    
        public virtual SysTask SysTask { get; set; }
    }
}
