//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFile
    {
        public string DcdUserID { get; set; }
        public string PassWord { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZIP { get; set; }
        public string Country { get; set; }
        public string OfficePhone { get; set; }
        public string Phone { get; set; }
        public string EMailAddress { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public int LastTime { get; set; }
        public bool UserDisabled { get; set; }
        public bool SecurityMgr { get; set; }
        public bool CanChangeSaveSettings { get; set; }
        public bool SaveSettings { get; set; }
        public string CurComp { get; set; }
        public Nullable<System.DateTime> PwdLastChanged { get; set; }
        public int PwdExpiresDays { get; set; }
        public Nullable<System.DateTime> PwdExpires { get; set; }
        public int PwdGrace { get; set; }
        public string GroupList { get; set; }
        public string CompList { get; set; }
        public bool DspPayrollMgr { get; set; }
        public string PayrollMgr { get; set; }
        public int ShpTrackerIntMinute { get; set; }
        public bool ViewFavoriteBar { get; set; }
        public bool ViewMenuTree { get; set; }
        public bool ViewStatusBar { get; set; }
        public int WinX { get; set; }
        public int WinY { get; set; }
        public int FavBarWidth { get; set; }
        public int MenuTreeWidth { get; set; }
        public int CurFolderSeq { get; set; }
        public string CurMenuID { get; set; }
        public int WinWidth { get; set; }
        public int WinHeight { get; set; }
        public bool DispTips { get; set; }
        public bool CanChangePassword { get; set; }
        public string LangNameID { get; set; }
        public string LastGraphType { get; set; }
        public bool AllowReq { get; set; }
        public string JCDept { get; set; }
        public bool UseInternalWebBrowser { get; set; }
        public bool AllowMultipleSessions { get; set; }
        public bool WebUser { get; set; }
        public int ListViewMode { get; set; }
        public bool CanMaintainFavQueries { get; set; }
        public bool CanMaintainFavURLs { get; set; }
        public bool CanMaintainFavPrograms { get; set; }
        public bool CanCustomize { get; set; }
        public int ViewTreeOnly { get; set; }
        public int Timeout { get; set; }
        public bool CanPersonalize { get; set; }
        public bool CanTranslate { get; set; }
        public bool CanSuspend { get; set; }
        public bool CanEditCompAnnotations { get; set; }
        public bool CanEditUserAnnotations { get; set; }
        public string CanEditHelpLinks { get; set; }
        public bool AutoStartMonitor { get; set; }
        public int MonitorPollingInterval { get; set; }
        public string FormOpenMode { get; set; }
        public string EntConType { get; set; }
        public bool DashboardDeveloper { get; set; }
        public bool CanDesignQSearch { get; set; }
        public bool RequireSso { get; set; }
        public bool ViewStatusPanelUserID { get; set; }
        public bool ViewStatusPanelLanguage { get; set; }
        public bool ViewStatusPanelCompany { get; set; }
        public bool ViewStatusPanelPlant { get; set; }
        public bool ViewStatusPanelServer { get; set; }
        public bool ViewStatusPanelWorkstationID { get; set; }
        public int ServerNum { get; set; }
        public string DomainName { get; set; }
        public bool BPMAdvancedUser { get; set; }
        public int MaxGroupsFavorites { get; set; }
        public int MaxGroupsSystemMenu { get; set; }
        public string OSUserID { get; set; }
        public bool CanTheme { get; set; }
        public string FormatCulture { get; set; }
        public bool CanOverrideAllocations { get; set; }
        public bool GlbCompSM { get; set; }
        public bool CanUseEntSearch { get; set; }
        public bool CanAccEpiEverywhere { get; set; }
        public bool CanAcessMobile { get; set; }
        public string StartMenuClient { get; set; }
        public string StartMenuEWA { get; set; }
        public string StartMenuMobile { get; set; }
        public bool TERetrieveApproved { get; set; }
        public bool TERetrieveEntered { get; set; }
        public bool TERetrieveRejected { get; set; }
        public bool TERetrieveSubmitted { get; set; }
        public bool TERetrievePartiallyApproved { get; set; }
        public bool TEAprRetrieveApproved { get; set; }
        public bool TEAprRetrieveEntered { get; set; }
        public bool TEAprRetrieveRejected { get; set; }
        public bool TEAprRetrieveSubmitted { get; set; }
        public bool TEAprRetrievePartiallyApproved { get; set; }
        public bool AdvBAQRights { get; set; }
        public bool SecurityAccessOnly { get; set; }
        public bool SolutionMgrCreate { get; set; }
        public bool SolutionMgrInstall { get; set; }
        public string EntSearchURL { get; set; }
        public bool CanMaintQuickSearch { get; set; }
        public bool UseDefaultEntSearch { get; set; }
        public bool UserAccessOnly { get; set; }
        public string MobilePassword { get; set; }
        public string ShopTrackerReuseLast { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public bool AdvancedConfiguratorUser { get; set; }
    }
}
