//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_BillOfMaterials
    {
        public string PartNum { get; set; }
        public string MtlPartNum { get; set; }
        public string PartDescription { get; set; }
        public string TypeCode { get; set; }
        public bool InActive { get; set; }
        public decimal QtyPer { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public Nullable<int> VendorNum { get; set; }
        public string PersonID { get; set; }
        public string BuyerID { get; set; }
        public Nullable<decimal> MfgLotSize { get; set; }
        public string VendorID { get; set; }
        public string RevisionNum { get; set; }
        public bool FixedQty { get; set; }
        public int RelatedOperation { get; set; }
        public int MtlSeq { get; set; }
        public string Name { get; set; }
        public bool PhantomBOM { get; set; }
        public Nullable<decimal> LastMaterialCost { get; set; }
        public bool ViewAsAsm { get; set; }
        public string ClassID { get; set; }
        public string AltMethod { get; set; }
        public Nullable<decimal> LastSubContCost { get; set; }
        public Nullable<decimal> LastMtlBurCost { get; set; }
        public Nullable<decimal> LastLaborCost { get; set; }
        public Nullable<decimal> LastBurdenCost { get; set; }
        public Nullable<int> LeadTime { get; set; }
        public string OpCode { get; set; }
        public Nullable<decimal> binqtyonhand { get; set; }
        public Nullable<decimal> onhandqty { get; set; }
        public Nullable<decimal> AllocQty { get; set; }
        public Nullable<decimal> UnfirmAllocQty { get; set; }
        public string Latest_Rev { get; set; }
        public string Current_Rev { get; set; }
        public string VenPartNum { get; set; }
        public Nullable<int> OpenJobCount { get; set; }
        public Nullable<int> OpenJobs { get; set; }
        public System.Guid Id { get; set; }
    }
}
