//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DistributorOrderList
    {
        public int OrderNum { get; set; }
        public string Name { get; set; }
        public int CustNum { get; set; }
        public string PONum { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> NeedByDate { get; set; }
        public int OrderLine { get; set; }
        public string PartNum { get; set; }
        public string LineDesc { get; set; }
        public decimal OrderQty { get; set; }
        public bool OpenLine { get; set; }
        public string ProdCode { get; set; }
        public System.Guid Id { get; set; }
    }
}
