//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_JobInformation_NotClosed
    {
        public int OrderNum { get; set; }
        public string JobNum { get; set; }
        public string PartNum { get; set; }
        public string SerialNumber { get; set; }
        public string SNStatus { get; set; }
        public Nullable<bool> JobClosed { get; set; }
        public Nullable<bool> JobComplete { get; set; }
        public Nullable<bool> JobEngineered { get; set; }
        public Nullable<bool> JobReleased { get; set; }
        public Nullable<bool> JobHeld { get; set; }
        public Nullable<bool> JobFirm { get; set; }
        public Nullable<System.DateTime> ReqDueDate { get; set; }
        public int OrderLine { get; set; }
        public int OrderRelNum { get; set; }
        public string ShipToNum { get; set; }
        public Nullable<int> CustNum { get; set; }
        public string ShipToname { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZIP { get; set; }
        public string Country { get; set; }
        public string CustName { get; set; }
        public string PONum { get; set; }
        public string CustID { get; set; }
        public System.Guid ID { get; set; }
    }
}
