//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_QuoteOrderInformation
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string ponum { get; set; }
        public string partnum { get; set; }
        public string linedesc { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
        public Nullable<System.DateTime> entrydate { get; set; }
        public string changedby { get; set; }
        public int QuoteReference { get; set; }
        public System.Guid Id1 { get; set; }
    }
}
