//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WhereUsed
    {
        public string PartNum { get; set; }
        public string RevisionNum { get; set; }
        public string PartDescription { get; set; }
        public string TypeCode { get; set; }
        public Nullable<bool> InActive { get; set; }
        public decimal QtyPer { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public Nullable<int> VendorNum { get; set; }
        public string PersonID { get; set; }
        public string BuyerID { get; set; }
        public string VendorID { get; set; }
        public Nullable<decimal> binqtyonhand { get; set; }
        public Nullable<decimal> LastMaterialCost { get; set; }
        public string VenPartNum { get; set; }
        public string Latest_Rev { get; set; }
        public Nullable<int> OpenJobCount { get; set; }
        public string Name { get; set; }
        public Nullable<bool> PhantomBOM { get; set; }
        public Nullable<decimal> OnHandQty { get; set; }
        public Nullable<int> OpenJobs { get; set; }
        public string MtlPartNum { get; set; }
        public bool FixedQty { get; set; }
        public int RelatedOperation { get; set; }
        public int MtlSeq { get; set; }
        public bool ViewAsAsm { get; set; }
        public System.Guid Id { get; set; }
        public string WarehouseCode { get; set; }
        public string Plant { get; set; }
    }
}
