//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Epicor.EntityModels.Epicor
{
    using System;
    using System.Collections.Generic;
    
    public partial class impartbin
    {
        public Nullable<decimal> intqueid { get; set; }
        public string company { get; set; }
        public string partnum { get; set; }
        public string warehousecode { get; set; }
        public string binnum { get; set; }
        public string incomingoutgoing { get; set; }
        public Nullable<decimal> onhandqty { get; set; }
        public string lotnum { get; set; }
        public string dimcode { get; set; }
        public string character01 { get; set; }
        public string character02 { get; set; }
        public string character03 { get; set; }
        public string character04 { get; set; }
        public string character05 { get; set; }
        public string character06 { get; set; }
        public string character07 { get; set; }
        public string character08 { get; set; }
        public string character09 { get; set; }
        public string character10 { get; set; }
        public Nullable<decimal> number01 { get; set; }
        public Nullable<decimal> number02 { get; set; }
        public Nullable<decimal> number03 { get; set; }
        public Nullable<decimal> number04 { get; set; }
        public Nullable<decimal> number05 { get; set; }
        public Nullable<decimal> number06 { get; set; }
        public Nullable<decimal> number07 { get; set; }
        public Nullable<decimal> number08 { get; set; }
        public Nullable<decimal> number09 { get; set; }
        public Nullable<decimal> number10 { get; set; }
        public Nullable<System.DateTime> date01 { get; set; }
        public Nullable<System.DateTime> date02 { get; set; }
        public Nullable<System.DateTime> date03 { get; set; }
        public Nullable<System.DateTime> date04 { get; set; }
        public Nullable<System.DateTime> date05 { get; set; }
        public Nullable<byte> checkbox01 { get; set; }
        public Nullable<byte> checkbox02 { get; set; }
        public Nullable<byte> checkbox03 { get; set; }
        public Nullable<byte> checkbox04 { get; set; }
        public Nullable<byte> checkbox05 { get; set; }
        public string intstatus { get; set; }
        public Nullable<byte> interror { get; set; }
        public Nullable<byte> intcomplete { get; set; }
        public Nullable<long> PROGRESS_RECID { get; set; }
        public long PROGRESS_RECID_IDENT_ { get; set; }
    }
}
