//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Legacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public string CompanyId { get; set; }
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Phone { get; set; }
        public string CustomerCode { get; set; }
        public string Salesman { get; set; }
        public string Salesman2 { get; set; }
        public string Salesman3 { get; set; }
        public string Salesman4 { get; set; }
        public string Salesman5 { get; set; }
        public Nullable<float> DiscountPercent { get; set; }
        public string Location { get; set; }
        public string ContactName { get; set; }
    }
}
