//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Legacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public string PartNumber { get; set; }
        public string Description { get; set; }
        public string Vendor { get; set; }
        public string Vendor2 { get; set; }
        public string Vendor3 { get; set; }
        public string VendorPartNumber { get; set; }
        public string AdditionalDescription { get; set; }
        public string AdditionalDescription2 { get; set; }
        public Nullable<decimal> AggrBuyoutCost { get; set; }
        public Nullable<decimal> AggrLaborCost { get; set; }
        public Nullable<decimal> CurrentMaterialCost { get; set; }
        public Nullable<System.DateTime> DateLastOrdered { get; set; }
        public Nullable<System.DateTime> DateLastRecieved { get; set; }
        public Nullable<System.DateTime> DateLastSold { get; set; }
        public string DrawingDate { get; set; }
        public string DrawingRevision { get; set; }
        public string DrawingSize { get; set; }
        public Nullable<decimal> IncrBuyoutCost { get; set; }
        public Nullable<decimal> IncrLaborCost { get; set; }
        public Nullable<decimal> IncrLastPurchaseCost { get; set; }
        public string LiftRequired { get; set; }
        public string LiftRequired2 { get; set; }
        public string LiftRequired3 { get; set; }
        public Nullable<decimal> ListPrice { get; set; }
        public string PartType { get; set; }
        public string PartsExpediteFlag { get; set; }
        public string Phantom { get; set; }
        public Nullable<decimal> UnitPrice2 { get; set; }
        public Nullable<decimal> UnitPrice3 { get; set; }
        public Nullable<decimal> UnitPrice4 { get; set; }
        public Nullable<decimal> UnitPrice5 { get; set; }
        public Nullable<decimal> UnitPrice6 { get; set; }
    }
}
