//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Legacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceLineItem
    {
        public string CompanyId { get; set; }
        public string InvoiceNumber { get; set; }
        public string LineNumber { get; set; }
        public string LineType { get; set; }
        public string Description { get; set; }
        public string UnitPerMeasure { get; set; }
        public string PriceCD { get; set; }
        public string Taxable { get; set; }
        public string Commissionable { get; set; }
        public string DropShip { get; set; }
        public string VendorNumber { get; set; }
        public string Location { get; set; }
        public string DistributionCode { get; set; }
        public string Kitted { get; set; }
        public string ProdCode { get; set; }
        public string KitOrdered { get; set; }
        public string CommunityCode { get; set; }
        public string MiscCode { get; set; }
        public string ProductCode { get; set; }
        public string PartNumber { get; set; }
        public string Warehouse { get; set; }
        public Nullable<float> QtyOrdered { get; set; }
        public Nullable<float> QtyShipped { get; set; }
        public Nullable<float> QtyBackordered { get; set; }
        public Nullable<decimal> PriceUnit { get; set; }
        public Nullable<decimal> PriceExtended { get; set; }
        public Nullable<float> CostUnit { get; set; }
        public Nullable<float> Discount { get; set; }
        public Nullable<float> QtyOriginalOrder { get; set; }
        public Nullable<float> CommissionRate { get; set; }
        public Nullable<decimal> CostExtened { get; set; }
        public Nullable<float> ClosedFromWo { get; set; }
    }
}
