//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Legacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEGACYSWO02Hb
    {
        public string Company { get; set; }
        public string WorkOrderNumber { get; set; }
        public string StepNumber { get; set; }
        public string LineType { get; set; }
        public string Comments { get; set; }
    }
}
