//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Legacy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LegacyEntities : DbContext
    {
        public LegacyEntities()
            : base("name=LegacyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<InvoiceHeader> InvoiceHeaders { get; set; }
        public virtual DbSet<InvoiceLineItem> InvoiceLineItems { get; set; }
        public virtual DbSet<InvoiceShipTo> InvoiceShipToes { get; set; }
        public virtual DbSet<LEGACYSWO011H> LEGACYSWO011H { get; set; }
        public virtual DbSet<LEGACYSWO02Hb> LEGACYSWO02Hb { get; set; }
        public virtual DbSet<LiftCost> LiftCosts { get; set; }
        public virtual DbSet<PartStep> PartSteps { get; set; }
        public virtual DbSet<PartStepDetail> PartStepDetails { get; set; }
        public virtual DbSet<PartXRef> PartXRefs { get; set; }
        public virtual DbSet<PullSheetHistory> PullSheetHistories { get; set; }
        public virtual DbSet<PurchaseBOM> PurchaseBOMs { get; set; }
        public virtual DbSet<PurchaseBOMItem> PurchaseBOMItems { get; set; }
        public virtual DbSet<PurchaseHistory> PurchaseHistories { get; set; }
        public virtual DbSet<RedrillPartXRef> RedrillPartXRefs { get; set; }
        public virtual DbSet<SerNoMemo> SerNoMemoes { get; set; }
        public virtual DbSet<SupplierInformation> SupplierInformations { get; set; }
        public virtual DbSet<WarrantyComponent> WarrantyComponents { get; set; }
        public virtual DbSet<WarrantyEndUser> WarrantyEndUsers { get; set; }
        public virtual DbSet<WarrantyInformation> WarrantyInformations { get; set; }
        public virtual DbSet<WarrantyInvoice> WarrantyInvoices { get; set; }
        public virtual DbSet<PurchaseHistory_Mods> PurchaseHistory_Mods { get; set; }
    }
}
