//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Legacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartStepDetail
    {
        public int Id { get; set; }
        public int CostStepListingId { get; set; }
        public string RecEOQ { get; set; }
        public string Step { get; set; }
        public string WorkCenter { get; set; }
        public string OpCode { get; set; }
        public string Description { get; set; }
        public string BaseQty { get; set; }
        public string FixedHours { get; set; }
        public string CrewSize { get; set; }
        public string VarHours { get; set; }
    
        public virtual PartStep PartStep { get; set; }
    }
}
