//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Legacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseBOM
    {
        public PurchaseBOM()
        {
            this.PurchaseBOMItems = new HashSet<PurchaseBOMItem>();
        }
    
        public int Id { get; set; }
        public string PartNumber { get; set; }
        public string VendorNumber { get; set; }
    
        public virtual ICollection<PurchaseBOMItem> PurchaseBOMItems { get; set; }
    }
}
