//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Legacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseBOMItem
    {
        public int Id { get; set; }
        public int PurchaseBOMId { get; set; }
        public string ULPartNumber { get; set; }
        public string VendorNumber { get; set; }
        public int LineNumber { get; set; }
        public string PartNumber { get; set; }
        public string TimePartNumber { get; set; }
        public float Qty { get; set; }
        public string Description { get; set; }
    
        public virtual PurchaseBOM PurchaseBOM { get; set; }
    }
}
