//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Legacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierInformation
    {
        public int Id { get; set; }
        public string PurchaseId { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Phone { get; set; }
        public string PurchaseAddress1 { get; set; }
        public string PurchaseAddress2 { get; set; }
        public string PurchaseAddress3 { get; set; }
        public string PurchaseCode { get; set; }
        public string PurchaseName { get; set; }
        public string PurchasePhone { get; set; }
    }
}
