//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Legacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarrantyInvoice
    {
        public int Id { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string InvoiceNumber { get; set; }
        public string CompanyId { get; set; }
        public string CustomerId { get; set; }
        public string PoNumber { get; set; }
        public string SalesOrderNumber { get; set; }
        public string LiftOrderNumber { get; set; }
    }
}
