//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.OrderLog
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiftModel
    {
        public LiftModel()
        {
            this.OrderTrans = new HashSet<OrderTran>();
        }
    
        public int LiftModelId { get; set; }
        public string LiftModelName { get; set; }
    
        public virtual ICollection<OrderTran> OrderTrans { get; set; }
    }
}
