//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.OrderLog
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTran
    {
        public int OrderTranId { get; set; }
        public int OrderId { get; set; }
        public int LiftModelId { get; set; }
        public int NewQty { get; set; }
        public int CancelQty { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> AsOfDate { get; set; }
        public bool Special { get; set; }
        public bool Stock { get; set; }
        public bool Demo { get; set; }
        public bool RTG { get; set; }
    
        public virtual LiftModel LiftModel { get; set; }
        public virtual Order Order { get; set; }
    }
}
