//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.OrderLog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Territory
    {
        public Territory()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int TerritoryId { get; set; }
        public int RegionId { get; set; }
        public string TerritoryName { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Region Region { get; set; }
    }
}
