//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.TimeMFG
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadListJobStatu
    {
        public int Id { get; set; }
        public int LoadListJobId { get; set; }
        public string JobNumber { get; set; }
        public int AssemblySeq { get; set; }
        public int OprSeq { get; set; }
        public string OpCode { get; set; }
        public byte OpComplete { get; set; }
        public Nullable<byte> IgnoreFlag { get; set; }
    
        public virtual LoadListJob LoadListJob { get; set; }
    }
}
