//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.TimeMFG
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadListComment
    {
        public int Id { get; set; }
        public int LoadListId { get; set; }
        public System.DateTime Date { get; set; }
        public string EnteredBy { get; set; }
        public string Comment { get; set; }
    
        public virtual LoadList LoadList { get; set; }
    }
}
