//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.TimeMFG
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadListJob
    {
        public LoadListJob()
        {
            this.LoadListJobComments = new HashSet<LoadListJobComment>();
            this.LoadListJobStatus = new HashSet<LoadListJobStatu>();
        }
    
        public int Id { get; set; }
        public int LoadListId { get; set; }
        public string JobNumber { get; set; }
        public string LiftModel { get; set; }
        public string SerialNo { get; set; }
        public string DistributorPO { get; set; }
        public System.DateTime DateATS { get; set; }
        public string Destination { get; set; }
        public string Comments { get; set; }
        public string CustomerName { get; set; }
        public int CustomerId { get; set; }
        public string ShipTo { get; set; }
        public string SalesOrder { get; set; }
    
        public virtual ICollection<LoadListJobComment> LoadListJobComments { get; set; }
        public virtual ICollection<LoadListJobStatu> LoadListJobStatus { get; set; }
        public virtual LoadList LoadList { get; set; }
    }
}
