//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.TimeMFG
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysTask
    {
        public int Id { get; set; }
        public bool Enabled { get; set; }
        public int SysTaskSchedNum { get; set; }
        public string Description { get; set; }
        public string TaskType { get; set; }
        public string TaskMessage { get; set; }
        public string SubmitUser { get; set; }
        public bool Recurring { get; set; }
        public string EmailRecipients { get; set; }
    
        public virtual SysTaskSchedule SysTaskSchedule { get; set; }
    }
}
