//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.TimeMFG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Term_ITInfo
    {
        public int Id { get; set; }
        public int EmpID { get; set; }
        public string WindowsAccAccess { get; set; }
        public bool ArchiveEmail { get; set; }
        public string EmailAtW { get; set; }
        public bool FowardEmails { get; set; }
        public string FowardAtW { get; set; }
        public bool DeleteUDrive { get; set; }
        public string UDriveAtW { get; set; }
        public bool DeskPhone { get; set; }
        public bool DeskPhoneFW { get; set; }
        public string DeskPhoneFWtW { get; set; }
        public bool DeskPhoneRename { get; set; }
        public string PhoneRenametW { get; set; }
        public bool EpicorAcc { get; set; }
        public string EpicorUserID { get; set; }
    
        public virtual Term_Employees Term_Employees { get; set; }
    }
}
