//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.TimeMFG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Term_Item
    {
        public int Id { get; set; }
        public int EmpID { get; set; }
        public string TypeOfItem { get; set; }
        public string Description { get; set; }
        public bool ItemReceived { get; set; }
    
        public virtual Term_Employees Term_Employees { get; set; }
    }
}
