//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.TimeMFG
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketAttachment
    {
        public int AttachmentID { get; set; }
        public int TicketID { get; set; }
        public string FileName { get; set; }
        public string FileExt { get; set; }
        public string Description { get; set; }
        public string UploadedBy { get; set; }
        public System.DateTime UploadedDate { get; set; }
    
        public virtual TicketProject TicketProject { get; set; }
    }
}
