//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.TimeMFG
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketEmployee
    {
        public TicketEmployee()
        {
            this.TicketDepartments = new HashSet<TicketDepartment>();
            this.TicketProjects = new HashSet<TicketProject>();
            this.TicketProjects1 = new HashSet<TicketProject>();
            this.TicketTasks = new HashSet<TicketTask>();
        }
    
        public int EmployeeID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Title { get; set; }
        public string NTLogin { get; set; }
        public string EmailName { get; set; }
        public string Extension { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<bool> InActive { get; set; }
    
        public virtual ICollection<TicketDepartment> TicketDepartments { get; set; }
        public virtual ICollection<TicketProject> TicketProjects { get; set; }
        public virtual ICollection<TicketProject> TicketProjects1 { get; set; }
        public virtual ICollection<TicketTask> TicketTasks { get; set; }
    }
}
