//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.TimeMFG
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketProject
    {
        public TicketProject()
        {
            this.TicketAttachments = new HashSet<TicketAttachment>();
            this.TicketLinks = new HashSet<TicketLink>();
            this.TicketLinks1 = new HashSet<TicketLink>();
            this.TicketNotes = new HashSet<TicketNote>();
            this.TicketStatusHistories = new HashSet<TicketStatusHistory>();
            this.TicketTasks = new HashSet<TicketTask>();
        }
    
        public int TicketID { get; set; }
        public int DepartmentID { get; set; }
        public int PriorityID { get; set; }
        public int CategoryID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public string PrivateNotes { get; set; }
        public string RequestedBy { get; set; }
        public string RequestedByFriendly { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public Nullable<int> AssignedEmployeeID { get; set; }
        public Nullable<int> ResourceEmployeeID { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ProjectBeginDate { get; set; }
        public Nullable<System.DateTime> ProjectEndDate { get; set; }
        public Nullable<int> TicketSequence { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string ApprovalCode { get; set; }
        public Nullable<bool> Focused { get; set; }
    
        public virtual ICollection<TicketAttachment> TicketAttachments { get; set; }
        public virtual TicketCategory TicketCategory { get; set; }
        public virtual TicketDepartment TicketDepartment { get; set; }
        public virtual TicketEmployee TicketEmployee { get; set; }
        public virtual TicketEmployee TicketEmployee1 { get; set; }
        public virtual ICollection<TicketLink> TicketLinks { get; set; }
        public virtual ICollection<TicketLink> TicketLinks1 { get; set; }
        public virtual ICollection<TicketNote> TicketNotes { get; set; }
        public virtual TicketPriority TicketPriority { get; set; }
        public virtual TicketStatus TicketStatus { get; set; }
        public virtual ICollection<TicketStatusHistory> TicketStatusHistories { get; set; }
        public virtual ICollection<TicketTask> TicketTasks { get; set; }
    }
}
