//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.TimeMFG
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ClassIdSummary
    {
        public string ClassId { get; set; }
        public Nullable<decimal> ExtCost { get; set; }
        public System.DateTime ComparisonDate { get; set; }
    }
}
