//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.TimeMFG
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaterTest
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public System.DateTime Date { get; set; }
        public int GallonsUsed { get; set; }
        public decimal PH { get; set; }
        public decimal Temp { get; set; }
        public System.DateTime SysDateTime { get; set; }
        public string SysUser { get; set; }
        public string SysComputer { get; set; }
    }
}
