//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Install
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChassisSpecsForWordDoc
    {
        public int Id { get; set; }
        public int LiftFamilyId { get; set; }
        public string CbToAxDimension { get; set; }
        public string FrmSctnModulus { get; set; }
        public string FrmRsistngBndngMmnt { get; set; }
        public string FrontGAWR { get; set; }
        public string RearGAWR { get; set; }
        public string GVWR { get; set; }
        public string AprxCrbWghtStblty { get; set; }
    
        public virtual LiftFamily LiftFamily { get; set; }
    }
}
