//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Install
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallQuote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstallQuote()
        {
            this.InstallDetails = new HashSet<InstallDetail>();
            this.InstallDetailsManuallyAddedOptions = new HashSet<InstallDetailsManuallyAddedOption>();
            this.QuoteChangesLogs = new HashSet<QuoteChangesLog>();
        }
    
        public int Id { get; set; }
        public string LiftName { get; set; }
        public int LiftQuoteNumber { get; set; }
        public int LiftQuoteLine { get; set; }
        public int LiftInstallLine { get; set; }
        public string InstallQuotedBy { get; set; }
        public System.DateTime QuoteDate { get; set; }
        public decimal TotalPriceLabor { get; set; }
        public decimal TotalPriceMaterial { get; set; }
        public Nullable<decimal> TotalInstallPrice { get; set; }
        public decimal TotalInstallHours { get; set; }
        public decimal TotalPaintHours { get; set; }
        public int LiftFamilyId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstallDetail> InstallDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstallDetailsManuallyAddedOption> InstallDetailsManuallyAddedOptions { get; set; }
        public virtual LiftFamily LiftFamily { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuoteChangesLog> QuoteChangesLogs { get; set; }
    }
}
