//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Install
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallDetailsManuallyAddedOption
    {
        public int Id { get; set; }
        public int InstallQuoteId { get; set; }
        public string OptionName { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> ExtendedPrice { get; set; }
        public Nullable<decimal> InstallHours { get; set; }
        public bool PaintFlag { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string OptionStatus { get; set; }
    
        public virtual InstallQuote InstallQuote { get; set; }
    }
}
