//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Install
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionTitleDescpForWordDoc
    {
        public int Id { get; set; }
        public int LiftFamilyId { get; set; }
        public int OptionTitlesId { get; set; }
        public string Description { get; set; }
    
        public virtual LiftFamily LiftFamily { get; set; }
        public virtual OptionTitlesForWordDoc OptionTitlesForWordDoc { get; set; }
    }
}
