//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Install
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartRev
    {
        public string Company { get; set; }
        public string PartNum { get; set; }
        public string RevisionNum { get; set; }
        public string RevShortDesc { get; set; }
        public string RevDescription { get; set; }
        public bool Approved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public decimal TLRLaborCost { get; set; }
        public decimal TLRBurdenCost { get; set; }
        public decimal TLRMaterialCost { get; set; }
        public decimal TLRSubcontractCost { get; set; }
        public decimal TLRMtlBurCost { get; set; }
        public decimal TLRSetupLaborCost { get; set; }
        public decimal TLRSetupBurdenCost { get; set; }
        public decimal LLRLaborCost { get; set; }
        public decimal LLRBurdenCost { get; set; }
        public decimal LLRMaterialCost { get; set; }
        public decimal LLRSubcontractCost { get; set; }
        public decimal LLRMtlBurCost { get; set; }
        public decimal LLRSetupLaborCost { get; set; }
        public decimal LLRSetupBurdenCost { get; set; }
        public Nullable<System.DateTime> RollupDate { get; set; }
        public string DrawNum { get; set; }
        public string ECO { get; set; }
        public bool Method { get; set; }
        public int AutoRecOpr { get; set; }
        public int FinalOpr { get; set; }
        public string PDMObjID { get; set; }
        public bool Configured { get; set; }
        public bool WebConfigured { get; set; }
        public bool ShowInputPrice { get; set; }
        public string AltMethod { get; set; }
        public string AltMethodDesc { get; set; }
        public string Plant { get; set; }
        public string ParentAltMethod { get; set; }
        public bool UseStaging { get; set; }
        public bool UseAltRevForParts { get; set; }
        public string OwnershipStatus { get; set; }
        public bool ExtConfig { get; set; }
        public bool ValRefDes { get; set; }
        public bool PcGlobalPart { get; set; }
        public bool PcEntprsConf { get; set; }
        public bool GlobalRev { get; set; }
        public string RoughCutCode { get; set; }
        public string RMAInspPlan { get; set; }
        public string RMASpecID { get; set; }
        public decimal RMASampleSize { get; set; }
        public decimal RMASampleSizePct { get; set; }
        public string BasePartNum { get; set; }
        public string BaseRevisionNum { get; set; }
        public string ConfigID { get; set; }
        public bool RegenConfig { get; set; }
        public int SIValuesGroupSeq { get; set; }
        public int SIValuesHeadNum { get; set; }
        public bool ExternalMES { get; set; }
        public byte[] SysRevID { get; set; }
        public System.Guid SysRowID { get; set; }
        public string ProcessMode { get; set; }
        public bool DefaultConfigPart { get; set; }
        public decimal CoPartsReqQty { get; set; }
        public decimal MtlCostPct { get; set; }
        public decimal LaborCostPct { get; set; }
        public int CoPartsPerOp { get; set; }
    }
}
