//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Install
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VSWQuotesEntities : DbContext
    {
        public VSWQuotesEntities()
            : base("name=VSWQuotesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InstallDetail> InstallDetails { get; set; }
        public virtual DbSet<InstallDetailsManuallyAddedOption> InstallDetailsManuallyAddedOptions { get; set; }
        public virtual DbSet<InstallHourlyRate> InstallHourlyRates { get; set; }
        public virtual DbSet<InstallQuote> InstallQuotes { get; set; }
        public virtual DbSet<LiftFamily> LiftFamilies { get; set; }
        public virtual DbSet<OptionGroup> OptionGroups { get; set; }
        public virtual DbSet<TimeOption> TimeOptions { get; set; }
        public virtual DbSet<VSWOption> VSWOptions { get; set; }
    }
}
