//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Versalift
{
    using System;
    using System.Collections.Generic;
    
    public partial class E10_DLS
    {
        public int ID { get; set; }
        public string CustNum { get; set; }
        public string CustName { get; set; }
        public string CustPO { get; set; }
        public string Model { get; set; }
        public string Lift { get; set; }
        public string Sales { get; set; }
        public string Serial { get; set; }
        public Nullable<System.DateTime> ATS { get; set; }
        public Nullable<System.DateTime> ATSCurr { get; set; }
        public System.DateTime LastChangedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
