//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.OrderLog.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLineUnit
    {
        public int OrderLineUnitId { get; set; }
        public int OrderLineId { get; set; }
        public Nullable<System.DateTime> ATSDate { get; set; }
        public string SalesOrderNum { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> InvoiceAmt { get; set; }
        public string UnitComment { get; set; }
        public bool Cancel { get; set; }
    
        public virtual OrderLine OrderLine { get; set; }
    }
}
