//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.OrderLog.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        public OrderLine()
        {
            this.OrderLineUnits = new HashSet<OrderLineUnit>();
        }
    
        public int OrderLineId { get; set; }
        public int OrderId { get; set; }
        public int LiftModelId { get; set; }
        public int NewQty { get; set; }
        public int CancelQty { get; set; }
        public bool Special { get; set; }
        public int InstallId { get; set; }
        public bool Stock { get; set; }
        public bool RTG { get; set; }
        public bool Demo { get; set; }
        public string Customer { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Comment { get; set; }
    
        public virtual Install Install { get; set; }
        public virtual LiftModel LiftModel { get; set; }
        public virtual Order Order { get; set; }
        public virtual ICollection<OrderLineUnit> OrderLineUnits { get; set; }
    }
}
