//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.CustomManuals
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CustomManualsEntities : DbContext
    {
        public CustomManualsEntities()
            : base("name=CustomManualsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Formatting> Formattings { get; set; }
        public virtual DbSet<LanguageCode> LanguageCodes { get; set; }
        public virtual DbSet<LiftGroup> LiftGroups { get; set; }
        public virtual DbSet<LiftOption> LiftOptions { get; set; }
        public virtual DbSet<Lift> Lifts { get; set; }
        public virtual DbSet<LocalMessage> LocalMessages { get; set; }
        public virtual DbSet<NoPrint> NoPrints { get; set; }
        public virtual DbSet<OptionPart> OptionParts { get; set; }
        public virtual DbSet<ProblemJob> ProblemJobs { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
    }
}
