//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.CustomManuals
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formatting
    {
        public int Formatting_ID { get; set; }
        public string Lift_Group { get; set; }
        public int Sequence { get; set; }
        public string Section { get; set; }
        public string PullsFrom { get; set; }
        public string Title { get; set; }
        public string EmptyPageL { get; set; }
        public string EmptyPageR { get; set; }
        public string BlankPage { get; set; }
        public Nullable<int> SectionStarts { get; set; }
        public bool PageNumbers { get; set; }
        public bool BlankPageMsg { get; set; }
        public bool CheckFacings { get; set; }
        public bool Active { get; set; }
    
        public virtual LiftGroup LiftGroup { get; set; }
    }
}
