//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.CustomManuals
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageCode
    {
        public LanguageCode()
        {
            this.LocalMessages = new HashSet<LocalMessage>();
        }
    
        public int Language_ID { get; set; }
        public string Language_Code { get; set; }
        public string Language { get; set; }
    
        public virtual ICollection<LocalMessage> LocalMessages { get; set; }
    }
}
