//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.CustomManuals
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiftOption
    {
        public LiftOption()
        {
            this.OptionParts = new HashSet<OptionPart>();
        }
    
        public int Id { get; set; }
        public string OptionNo { get; set; }
        public string Title { get; set; }
        public string ShortTitle { get; set; }
        public bool Active { get; set; }
        public bool DistributorViewable { get; set; }
    
        public virtual ICollection<OptionPart> OptionParts { get; set; }
    }
}
