//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.CustomManuals
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalMessage
    {
        public int ID { get; set; }
        public int LanguageID { get; set; }
        public string Name { get; set; }
        public string MessageText { get; set; }
    
        public virtual LanguageCode LanguageCode { get; set; }
    }
}
