//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.CustomManuals
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionPart
    {
        public int Id { get; set; }
        public int LiftOptionId { get; set; }
        public string Part { get; set; }
        public int Sequence { get; set; }
    
        public virtual LiftOption LiftOption { get; set; }
    }
}
