//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.CustomManuals
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProblemJob
    {
        public int Id { get; set; }
        public string JobNumber { get; set; }
        public string SerialNumber { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public string EntryPerson { get; set; }
        public string Problem { get; set; }
        public string Language { get; set; }
        public string Language_Code { get; set; }
        public System.DateTime RequiredDate { get; set; }
        public Nullable<System.DateTime> LastCheckedDate { get; set; }
        public string LastCheckedPerson { get; set; }
        public string LastCheckedMessage { get; set; }
        public bool JobCleared { get; set; }
        public Nullable<System.DateTime> JobClearedDate { get; set; }
        public string JobClearedBy { get; set; }
        public Nullable<bool> ManuallyCleared { get; set; }
        public string ManuallyClearedBy { get; set; }
        public string ManuallyClearedNote { get; set; }
        public string AutomaticEntryReason { get; set; }
    }
}
