//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.CustomManuals
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Settings_ID { get; set; }
        public string Setting1 { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
        public bool Required { get; set; }
    }
}
