//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Admin.EntityModels.Versalift
{
    using System;
    using System.Collections.Generic;
    
    public partial class VersaliftLiftModelAttribute
    {
        public int AttributeID { get; set; }
        public int ModelID { get; set; }
        public int Type { get; set; }
        public string Value { get; set; }
        public int Rank { get; set; }
        public bool isVisible { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual VersaliftLiftModelAttributeType VersaliftLiftModelAttributeType { get; set; }
        public virtual VersaliftLiftModel VersaliftLiftModel { get; set; }
    }
}
