//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Admin.EntityModels.Versalift
{
    using System;
    using System.Collections.Generic;
    
    public partial class VersaliftBaseModel
    {
        public int RID { get; set; }
        public string BaseModelName { get; set; }
        public string PictureURL { get; set; }
        public string MaxWorkingHeight { get; set; }
        public string MaxHorizontalReach { get; set; }
        public string MaxHorizontalReachNonOvercenter { get; set; }
        public string StowedTravelHeight { get; set; }
        public string MaxPlatformCapacity { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public string Custom3 { get; set; }
        public string Custom4 { get; set; }
        public string Custom5 { get; set; }
        public string Custom6 { get; set; }
        public string Custom7 { get; set; }
        public string Custom8 { get; set; }
        public string Custom9 { get; set; }
        public string Custom10 { get; set; }
    }
}
