//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Admin.EntityModels.Versalift
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VersaliftEntities : DbContext
    {
        public VersaliftEntities()
            : base("name=VersaliftEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VersaliftLiftCategory> VersaliftLiftCategories { get; set; }
        public virtual DbSet<VersaliftLiftModelAttribute> VersaliftLiftModelAttributes { get; set; }
        public virtual DbSet<VersaliftLiftModelAttributeType> VersaliftLiftModelAttributeTypes { get; set; }
        public virtual DbSet<VersaliftLiftModel> VersaliftLiftModels { get; set; }
        public virtual DbSet<VersaliftBaseModel> VersaliftBaseModels { get; set; }
    }
}
