//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Admin.EntityModels.Versalift
{
    using System;
    using System.Collections.Generic;
    
    public partial class VersaliftLiftModelAttributeType
    {
        public VersaliftLiftModelAttributeType()
        {
            this.VersaliftLiftModelAttributes = new HashSet<VersaliftLiftModelAttribute>();
        }
    
        public int AttributeTypeID { get; set; }
        public string AttributeName { get; set; }
    
        public virtual ICollection<VersaliftLiftModelAttribute> VersaliftLiftModelAttributes { get; set; }
    }
}
