//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Admin.EntityModels.Versalift
{
    using System;
    using System.Collections.Generic;
    
    public partial class VersaliftLiftCategory
    {
        public VersaliftLiftCategory()
        {
            this.VersaliftLiftModels = new HashSet<VersaliftLiftModel>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string CategoryGroup { get; set; }
        public int CategoryParentID { get; set; }
        public bool isEnabled { get; set; }
        public int Sequence { get; set; }
        public string OverrideURL { get; set; }
        public string VideoURL { get; set; }
    
        public virtual ICollection<VersaliftLiftModel> VersaliftLiftModels { get; set; }
    }
}
