//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Admin.EntityModels.Versalift
{
    using System;
    using System.Collections.Generic;
    
    public partial class VersaliftLiftModel
    {
        public VersaliftLiftModel()
        {
            this.VersaliftLiftModelAttributes = new HashSet<VersaliftLiftModelAttribute>();
            this.VersaliftLiftCategories = new HashSet<VersaliftLiftCategory>();
        }
    
        public int ModelID { get; set; }
        public Nullable<int> BaseModelID { get; set; }
        public string Model { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public int Height { get; set; }
        public bool isVisible { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool Condor { get; set; }
        public string VideoURL { get; set; }
    
        public virtual ICollection<VersaliftLiftModelAttribute> VersaliftLiftModelAttributes { get; set; }
        public virtual ICollection<VersaliftLiftCategory> VersaliftLiftCategories { get; set; }
    }
}
