//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Invoicing.EntityModels.Epicor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EpicorInvoiceEntities : DbContext
    {
        public EpicorInvoiceEntities()
            : base("name=EpicorInvoiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<orderrel> orderrels { get; set; }
        public virtual DbSet<jobprod> jobprods { get; set; }
        public virtual DbSet<orderdtl> orderdtls { get; set; }
        public virtual DbSet<serialno> serialnoes { get; set; }
    }
}
