//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Invoicing.EntityModels.Epicor
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobprod
    {
        public string company { get; set; }
        public string jobnum { get; set; }
        public Nullable<int> ordernum { get; set; }
        public Nullable<int> orderline { get; set; }
        public Nullable<int> orderrelnum { get; set; }
        public Nullable<decimal> prodqty { get; set; }
        public string warehousecode { get; set; }
        public string targetjobnum { get; set; }
        public Nullable<int> targetassemblyseq { get; set; }
        public Nullable<int> targetmtlseq { get; set; }
        public Nullable<decimal> shippedqty { get; set; }
        public Nullable<decimal> receivedqty { get; set; }
        public Nullable<decimal> allocatedqty { get; set; }
        public Nullable<int> callnum { get; set; }
        public Nullable<int> callline { get; set; }
        public string tflinenum { get; set; }
        public string partnum { get; set; }
        public string shortchar01 { get; set; }
        public string shortchar02 { get; set; }
        public string shortchar03 { get; set; }
        public string shortchar04 { get; set; }
        public string shortchar05 { get; set; }
        public Nullable<decimal> number01 { get; set; }
        public Nullable<decimal> number02 { get; set; }
        public Nullable<decimal> number03 { get; set; }
        public Nullable<decimal> number04 { get; set; }
        public Nullable<decimal> number05 { get; set; }
        public Nullable<System.DateTime> date01 { get; set; }
        public Nullable<System.DateTime> date02 { get; set; }
        public Nullable<System.DateTime> date03 { get; set; }
        public Nullable<System.DateTime> date04 { get; set; }
        public Nullable<System.DateTime> date05 { get; set; }
        public Nullable<byte> checkbox01 { get; set; }
        public Nullable<byte> checkbox02 { get; set; }
        public Nullable<byte> checkbox03 { get; set; }
        public Nullable<byte> checkbox04 { get; set; }
        public Nullable<byte> checkbox05 { get; set; }
        public string plant { get; set; }
        public Nullable<long> PROGRESS_RECID { get; set; }
        public long PROGRESS_RECID_IDENT_ { get; set; }
    }
}
