//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Invoicing.EntityModels.Epicor
{
    using System;
    using System.Collections.Generic;
    
    public partial class serialno
    {
        public string company { get; set; }
        public string partnum { get; set; }
        public string serialnumber { get; set; }
        public string snstatus { get; set; }
        public string jobnum { get; set; }
        public Nullable<int> assemblyseq { get; set; }
        public Nullable<int> mtlseq { get; set; }
        public Nullable<int> packnum { get; set; }
        public Nullable<int> packline { get; set; }
        public Nullable<byte> voided { get; set; }
        public Nullable<byte> scrapped { get; set; }
        public Nullable<int> vendornum { get; set; }
        public string purpoint { get; set; }
        public string packslip { get; set; }
        public Nullable<int> packslipline { get; set; }
        public Nullable<byte> selected { get; set; }
        public string prevsnstatus { get; set; }
        public string snprefix { get; set; }
        public string snformat { get; set; }
        public string snbasestructure { get; set; }
        public string snbasenumber { get; set; }
        public string scrapreasoncode { get; set; }
        public string snreference { get; set; }
        public Nullable<int> rmanum { get; set; }
        public Nullable<int> rmaline { get; set; }
        public Nullable<int> rmareceipt { get; set; }
        public Nullable<int> dmrnum { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> dmractionnum { get; set; }
        public Nullable<byte> failselect { get; set; }
        public Nullable<int> contractnum { get; set; }
        public Nullable<int> contractline { get; set; }
        public Nullable<int> linedetailnum { get; set; }
        public Nullable<int> rmadisp { get; set; }
        public Nullable<int> nonconfnum { get; set; }
        public string character01 { get; set; }
        public string character02 { get; set; }
        public string character03 { get; set; }
        public string character04 { get; set; }
        public string character05 { get; set; }
        public string character06 { get; set; }
        public string character07 { get; set; }
        public string character08 { get; set; }
        public string character09 { get; set; }
        public string character10 { get; set; }
        public Nullable<decimal> number01 { get; set; }
        public Nullable<decimal> number02 { get; set; }
        public Nullable<decimal> number03 { get; set; }
        public Nullable<decimal> number04 { get; set; }
        public Nullable<decimal> number05 { get; set; }
        public Nullable<decimal> number06 { get; set; }
        public Nullable<decimal> number07 { get; set; }
        public Nullable<decimal> number08 { get; set; }
        public Nullable<decimal> number09 { get; set; }
        public Nullable<decimal> number10 { get; set; }
        public Nullable<System.DateTime> date01 { get; set; }
        public Nullable<System.DateTime> date02 { get; set; }
        public Nullable<System.DateTime> date03 { get; set; }
        public Nullable<System.DateTime> date04 { get; set; }
        public Nullable<System.DateTime> date05 { get; set; }
        public Nullable<byte> checkbox01 { get; set; }
        public Nullable<byte> checkbox02 { get; set; }
        public Nullable<byte> checkbox03 { get; set; }
        public Nullable<byte> checkbox04 { get; set; }
        public Nullable<byte> checkbox05 { get; set; }
        public string warehousecode { get; set; }
        public string binnum { get; set; }
        public Nullable<System.DateTime> contexpiredate { get; set; }
        public Nullable<System.DateTime> warrexpiration { get; set; }
        public Nullable<int> custnum { get; set; }
        public string shiptonum { get; set; }
        public string createdby { get; set; }
        public string modifiedby { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<int> modifiedtime { get; set; }
        public string shippedfrom { get; set; }
        public Nullable<byte> tranadd { get; set; }
        public Nullable<int> temptranid { get; set; }
        public Nullable<int> tfpacknum { get; set; }
        public Nullable<int> tfpackline { get; set; }
        public Nullable<int> ordernum { get; set; }
        public Nullable<int> orderline { get; set; }
        public Nullable<int> orderrelnum { get; set; }
        public Nullable<long> PROGRESS_RECID { get; set; }
        public long PROGRESS_RECID_IDENT_ { get; set; }
    }
}
