//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Epicor
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysagentsched
    {
        public string agentid { get; set; }
        public Nullable<int> agentschednum { get; set; }
        public string scheddesc { get; set; }
        public string schedtype { get; set; }
        public Nullable<System.DateTime> nextrundate { get; set; }
        public Nullable<int> nextruntime { get; set; }
        public Nullable<int> recurrences { get; set; }
        public Nullable<System.DateTime> effectivedate { get; set; }
        public string monthlyoption { get; set; }
        public Nullable<int> dayofmonth { get; set; }
        public string weekofmonth { get; set; }
        public Nullable<int> dayofweek { get; set; }
        public Nullable<int> everynweeks { get; set; }
        public Nullable<System.DateTime> lastrundate { get; set; }
        public Nullable<int> lastruntime { get; set; }
        public Nullable<byte> mondays { get; set; }
        public Nullable<byte> tuesdays { get; set; }
        public Nullable<byte> wednesdays { get; set; }
        public Nullable<byte> thursdays { get; set; }
        public Nullable<byte> fridays { get; set; }
        public Nullable<byte> saturdays { get; set; }
        public Nullable<byte> sundays { get; set; }
        public Nullable<byte> enabled { get; set; }
        public string appsrvconnectionid { get; set; }
        public Nullable<int> intervaltime { get; set; }
        public Nullable<long> PROGRESS_RECID { get; set; }
        public long PROGRESS_RECID_IDENT_ { get; set; }
    }
}
