//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Epicor
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysagenttask
    {
        public string agentid { get; set; }
        public Nullable<int> agentschednum { get; set; }
        public Nullable<int> agenttasknum { get; set; }
        public string taskdesc { get; set; }
        public string tasktype { get; set; }
        public string runprocedure { get; set; }
        public string runmethod { get; set; }
        public Nullable<System.DateTime> submitdate { get; set; }
        public string submituser { get; set; }
        public Nullable<int> submittime { get; set; }
        public string parammaintprogram { get; set; }
        public string company { get; set; }
        public string tasknote { get; set; }
        public string processid { get; set; }
        public Nullable<int> processtasknum { get; set; }
        public Nullable<long> PROGRESS_RECID { get; set; }
        public long PROGRESS_RECID_IDENT_ { get; set; }
    }
}
