//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Epicor
{
    using System;
    using System.Collections.Generic;
    
    public partial class systaskkill
    {
        public Nullable<int> systasknum { get; set; }
        public Nullable<long> PROGRESS_RECID { get; set; }
        public long PROGRESS_RECID_IDENT_ { get; set; }
    }
}
