//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Epicor
{
    using System;
    using System.Collections.Generic;
    
    public partial class systask
    {
        public Nullable<int> systasknum { get; set; }
        public string taskdescription { get; set; }
        public string tasktype { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<int> starttime { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public Nullable<int> endtime { get; set; }
        public string submituser { get; set; }
        public string taskstatus { get; set; }
        public string company { get; set; }
        public string agentid { get; set; }
        public Nullable<int> agentschednum { get; set; }
        public Nullable<int> agenttasknum { get; set; }
        public string runprocedure { get; set; }
        public string initiatorsource { get; set; }
        public string activitymsg { get; set; }
        public Nullable<byte> history { get; set; }
        public string tasknote { get; set; }
        public Nullable<System.DateTime> lastactivitydate { get; set; }
        public Nullable<int> lastactivitytime { get; set; }
        public string userpidinfo { get; set; }
        public string processid { get; set; }
        public Nullable<long> PROGRESS_RECID { get; set; }
        public long PROGRESS_RECID_IDENT_ { get; set; }
    }
}
