//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Epicor
{
    using System;
    using System.Collections.Generic;
    
    public partial class systasklog
    {
        public Nullable<int> systasknum { get; set; }
        public Nullable<int> entrynum { get; set; }
        public Nullable<System.DateTime> entrydate { get; set; }
        public Nullable<int> entrytime { get; set; }
        public Nullable<byte> iserror { get; set; }
        public string msgtext { get; set; }
        public Nullable<long> PROGRESS_RECID { get; set; }
        public long PROGRESS_RECID_IDENT_ { get; set; }
    }
}
