//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Epicor
{
    using System;
    using System.Collections.Generic;
    
    public partial class systaskparam
    {
        public Nullable<int> systasknum { get; set; }
        public string paramname { get; set; }
        public string paramlabel { get; set; }
        public string paramtype { get; set; }
        public string paramdatatype { get; set; }
        public string paramcharacter { get; set; }
        public Nullable<System.DateTime> paramdate { get; set; }
        public Nullable<byte> paramlogical { get; set; }
        public Nullable<int> paraminteger { get; set; }
        public Nullable<decimal> paramdecimal { get; set; }
        public string paramtoken { get; set; }
        public Nullable<long> PROGRESS_RECID { get; set; }
        public long PROGRESS_RECID_IDENT_ { get; set; }
    }
}
