//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Epicor
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_CustomersWithOpenOrderPartLines
    {
        public Nullable<int> custnum { get; set; }
        public string name { get; set; }
        public Nullable<byte> openorder { get; set; }
        public Nullable<byte> voidorder { get; set; }
        public Nullable<int> ordernum { get; set; }
        public long Id { get; set; }
        public Nullable<int> orderline { get; set; }
        public string partnum { get; set; }
        public string salescatid { get; set; }
        public string prodcode { get; set; }
    }
}
