//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Epicor
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_PartDetails
    {
        public string partnum { get; set; }
        public string partdescription { get; set; }
        public string typecode { get; set; }
        public Nullable<byte> inactive { get; set; }
        public Nullable<byte> phantombom { get; set; }
        public Nullable<decimal> baseprice { get; set; }
        public Nullable<int> vendornum { get; set; }
        public string personid { get; set; }
        public string buyerid { get; set; }
        public string vendorid { get; set; }
        public string revisionnum { get; set; }
        public string eco { get; set; }
        public string drawnum { get; set; }
        public Nullable<decimal> onhandqty { get; set; }
        public string name { get; set; }
        public string classid { get; set; }
        public string subpart { get; set; }
        public string prodcode { get; set; }
        public Nullable<decimal> lastmaterialcost { get; set; }
        public string venpartnum { get; set; }
        public string binnum { get; set; }
        public Nullable<decimal> binqty { get; set; }
        public string buyername { get; set; }
        public Nullable<decimal> binqtyonhand { get; set; }
        public Nullable<int> OpenJobCount { get; set; }
        public long Id { get; set; }
    }
}
