//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.Epicor
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendpart
    {
        public string company { get; set; }
        public string partnum { get; set; }
        public string opcode { get; set; }
        public Nullable<System.DateTime> effectivedate { get; set; }
        public Nullable<int> vendornum { get; set; }
        public string pum { get; set; }
        public Nullable<int> leadtime { get; set; }
        public Nullable<decimal> purchasingfactor { get; set; }
        public Nullable<decimal> baseunitprice { get; set; }
        public string venpartnum { get; set; }
        public string priceformat { get; set; }
        public string pricepercode { get; set; }
        public Nullable<decimal> minimumprice { get; set; }
        public Nullable<System.DateTime> expirationdate { get; set; }
        public string reference { get; set; }
        public Nullable<decimal> miscamt { get; set; }
        public string misccode { get; set; }
        public string commenttext { get; set; }
        public Nullable<decimal> discountpercent { get; set; }
        public string partdescription { get; set; }
        public Nullable<int> rfqnum { get; set; }
        public Nullable<int> rfqline { get; set; }
        public string currencycode { get; set; }
        public string character01 { get; set; }
        public string character02 { get; set; }
        public string character03 { get; set; }
        public string character04 { get; set; }
        public string character05 { get; set; }
        public string character06 { get; set; }
        public string character07 { get; set; }
        public string character08 { get; set; }
        public string character09 { get; set; }
        public string character10 { get; set; }
        public Nullable<decimal> number01 { get; set; }
        public Nullable<decimal> number02 { get; set; }
        public Nullable<decimal> number03 { get; set; }
        public Nullable<decimal> number04 { get; set; }
        public Nullable<decimal> number05 { get; set; }
        public Nullable<decimal> number06 { get; set; }
        public Nullable<decimal> number07 { get; set; }
        public Nullable<decimal> number08 { get; set; }
        public Nullable<decimal> number09 { get; set; }
        public Nullable<decimal> number10 { get; set; }
        public Nullable<System.DateTime> date01 { get; set; }
        public Nullable<System.DateTime> date02 { get; set; }
        public Nullable<System.DateTime> date03 { get; set; }
        public Nullable<System.DateTime> date04 { get; set; }
        public Nullable<System.DateTime> date05 { get; set; }
        public Nullable<byte> checkbox01 { get; set; }
        public Nullable<byte> checkbox02 { get; set; }
        public Nullable<byte> checkbox03 { get; set; }
        public Nullable<byte> checkbox04 { get; set; }
        public Nullable<byte> checkbox05 { get; set; }
        public string mfgpartnum { get; set; }
        public Nullable<decimal> onhandqty { get; set; }
        public Nullable<System.DateTime> onhanddate { get; set; }
        public Nullable<int> onhandtime { get; set; }
        public Nullable<int> connum { get; set; }
        public Nullable<decimal> number11 { get; set; }
        public Nullable<decimal> number12 { get; set; }
        public Nullable<decimal> number13 { get; set; }
        public Nullable<decimal> number14 { get; set; }
        public Nullable<decimal> number15 { get; set; }
        public Nullable<decimal> number16 { get; set; }
        public Nullable<decimal> number17 { get; set; }
        public Nullable<decimal> number18 { get; set; }
        public Nullable<decimal> number19 { get; set; }
        public Nullable<decimal> number20 { get; set; }
        public Nullable<System.DateTime> date06 { get; set; }
        public Nullable<System.DateTime> date07 { get; set; }
        public Nullable<System.DateTime> date08 { get; set; }
        public Nullable<System.DateTime> date09 { get; set; }
        public Nullable<System.DateTime> date10 { get; set; }
        public Nullable<System.DateTime> date11 { get; set; }
        public Nullable<System.DateTime> date12 { get; set; }
        public Nullable<System.DateTime> date13 { get; set; }
        public Nullable<System.DateTime> date14 { get; set; }
        public Nullable<System.DateTime> date15 { get; set; }
        public Nullable<System.DateTime> date16 { get; set; }
        public Nullable<System.DateTime> date17 { get; set; }
        public Nullable<System.DateTime> date18 { get; set; }
        public Nullable<System.DateTime> date19 { get; set; }
        public Nullable<System.DateTime> date20 { get; set; }
        public Nullable<byte> checkbox06 { get; set; }
        public Nullable<byte> checkbox07 { get; set; }
        public Nullable<byte> checkbox08 { get; set; }
        public Nullable<byte> checkbox09 { get; set; }
        public Nullable<byte> checkbox10 { get; set; }
        public Nullable<byte> checkbox11 { get; set; }
        public Nullable<byte> checkbox12 { get; set; }
        public Nullable<byte> checkbox13 { get; set; }
        public Nullable<byte> checkbox14 { get; set; }
        public Nullable<byte> checkbox15 { get; set; }
        public Nullable<byte> checkbox16 { get; set; }
        public Nullable<byte> checkbox17 { get; set; }
        public Nullable<byte> checkbox18 { get; set; }
        public Nullable<byte> checkbox19 { get; set; }
        public Nullable<byte> checkbox20 { get; set; }
        public string shortchar01 { get; set; }
        public string shortchar02 { get; set; }
        public string shortchar03 { get; set; }
        public string shortchar04 { get; set; }
        public string shortchar05 { get; set; }
        public string shortchar06 { get; set; }
        public string shortchar07 { get; set; }
        public string shortchar08 { get; set; }
        public string shortchar09 { get; set; }
        public string shortchar10 { get; set; }
        public string purchasingfactordirection { get; set; }
        public Nullable<byte> supplierresponseready { get; set; }
        public Nullable<long> PROGRESS_RECID { get; set; }
        public long PROGRESS_RECID_IDENT_ { get; set; }
    }
}
