//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Drawings.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drawings_PDF
    {
        public Drawings_PDF()
        {
            this.AdditionalDrawings = new HashSet<Drawings_PDF>();
            this.SourceDrawing = new HashSet<Drawings_PDF>();
        }
    
        public int Id { get; set; }
        public string Drawing { get; set; }
        public string FileName { get; set; }
        public string Directory { get; set; }
        public Nullable<bool> Missing { get; set; }
        public Nullable<System.DateTime> LastChecked { get; set; }
    
        public virtual ICollection<Drawings_PDF> AdditionalDrawings { get; set; }
        public virtual ICollection<Drawings_PDF> SourceDrawing { get; set; }
    }
}
