//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.ITInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttachmentForModel
    {
        public int Id { get; set; }
        public int ModelId { get; set; }
        public string FileName { get; set; }
        public string FileExt { get; set; }
        public string Description { get; set; }
        public string UploadedBy { get; set; }
        public System.DateTime UploadedDate { get; set; }
    
        public virtual Ref_Model Ref_Model { get; set; }
    }
}
