//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.ITInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer
    {
        public Computer()
        {
            this.Ref_NIC = new HashSet<Ref_NIC>();
            this.ScheduledTasks = new HashSet<ScheduledTask>();
            this.Licenses = new HashSet<License>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int StatusId { get; set; }
        public int ModelId { get; set; }
        public string WindowsKey { get; set; }
        public Nullable<int> MemoryId { get; set; }
        public Nullable<int> ProcessorId { get; set; }
        public Nullable<int> DeviceTypeId { get; set; }
        public Nullable<int> OSId { get; set; }
        public Nullable<int> VideoCardId { get; set; }
        public Nullable<int> SoundId { get; set; }
        public string LastEditedBy { get; set; }
        public Nullable<System.DateTime> LastDateEdited { get; set; }
        public string Note { get; set; }
        public string PO { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string AssetTag { get; set; }
        public string BIOS_Version { get; set; }
        public Nullable<System.DateTime> WarrantyExpirationDate { get; set; }
        public string Notes { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> LastBuildDate { get; set; }
        public string PhoneNumber { get; set; }
        public string SerialNumber { get; set; }
        public string AdditionalHW { get; set; }
    
        public virtual Ref_Memory Ref_Memory { get; set; }
        public virtual Ref_Model Ref_Model { get; set; }
        public virtual Ref_Status Ref_Status { get; set; }
        public virtual Ref_VideoCard Ref_VideoCard { get; set; }
        public virtual Ref_DeviceType Ref_DeviceType { get; set; }
        public virtual Ref_OS Ref_OS { get; set; }
        public virtual Ref_Processor Ref_Processor { get; set; }
        public virtual Ref_Sound Ref_Sound { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Ref_NIC> Ref_NIC { get; set; }
        public virtual ICollection<ScheduledTask> ScheduledTasks { get; set; }
        public virtual ICollection<License> Licenses { get; set; }
    }
}
