//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.ITInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class License
    {
        public License()
        {
            this.Computers = new HashSet<Computer>();
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
        public string LicenseKey { get; set; }
        public int QuantityAssigned { get; set; }
        public Nullable<int> ComputerId { get; set; }
        public Nullable<int> LicenseTypeId { get; set; }
        public string PO { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string Note { get; set; }
    
        public virtual Ref_LicenseType Ref_LicenseType { get; set; }
        public virtual ICollection<Computer> Computers { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
