//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.ITInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceDataDetail
    {
        public int Id { get; set; }
        public int MaintenanceDataId { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public string AccountNumber { get; set; }
        public string Duration { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Monthly { get; set; }
        public string Explanation { get; set; }
        public string AlternateInfo { get; set; }
    
        public virtual MaintenanceData MaintenanceData { get; set; }
    }
}
