//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.ITInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceData
    {
        public MaintenanceData()
        {
            this.MaintenanceDataDetails = new HashSet<MaintenanceDataDetail>();
        }
    
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string BudgetItem { get; set; }
        public string Supplier { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<System.DateTime> OriginalPurchDate { get; set; }
        public Nullable<int> ComputerId { get; set; }
        public Nullable<int> LicenseId { get; set; }
    
        public virtual ICollection<MaintenanceDataDetail> MaintenanceDataDetails { get; set; }
    }
}
