//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.ITInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monitor
    {
        public Monitor()
        {
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public int ManufacturerId { get; set; }
        public string SerialNo { get; set; }
        public Nullable<int> AssetId { get; set; }
        public int SizeId { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string PurchasedFrom { get; set; }
        public string PO { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual Ref_Manufacturer Ref_Manufacturer { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual Ref_MonitorSizes Ref_MonitorSizes { get; set; }
    }
}
