//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.ITInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_NIC
    {
        public int Id { get; set; }
        public string MAC { get; set; }
        public string IP { get; set; }
        public Nullable<int> SpeedId { get; set; }
        public string Type { get; set; }
        public Nullable<int> SwitchPortId { get; set; }
        public Nullable<int> CableId { get; set; }
        public Nullable<int> ComputerId { get; set; }
    
        public virtual Computer Computer { get; set; }
        public virtual Ref_CableNo Ref_CableNo { get; set; }
        public virtual Ref_NICSpeed Ref_NICSpeed { get; set; }
        public virtual Ref_SwitchPort Ref_SwitchPort { get; set; }
    }
}
