//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.ITInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_Manufacturer
    {
        public Ref_Manufacturer()
        {
            this.Ref_Model = new HashSet<Ref_Model>();
            this.Monitors = new HashSet<Monitor>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Ref_Model> Ref_Model { get; set; }
        public virtual ICollection<Monitor> Monitors { get; set; }
    }
}
