//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.ITInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledTask
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int ComputerId { get; set; }
        public string Time { get; set; }
        public string DOM { get; set; }
        public bool Sunday { get; set; }
        public bool Monday { get; set; }
        public bool Tuesday { get; set; }
        public bool Wednesday { get; set; }
        public bool Thursday { get; set; }
        public bool Friday { get; set; }
        public bool Saturday { get; set; }
        public string Program { get; set; }
        public string SecurityRunAs { get; set; }
        public string Databases { get; set; }
        public string Purpose { get; set; }
        public string SharesLocations { get; set; }
        public string Notes { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual Computer Computer { get; set; }
    }
}
