//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Data.EntityModels.ITInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Computers = new HashSet<Computer>();
            this.Licenses = new HashSet<License>();
            this.Monitors = new HashSet<Monitor>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ComputerId { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> CableId { get; set; }
        public Nullable<int> SwitchPortId { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> LastEditedDate { get; set; }
        public string LastEditedby { get; set; }
    
        public virtual Ref_Building Ref_Building { get; set; }
        public virtual Ref_Location Ref_Location { get; set; }
        public virtual ICollection<Computer> Computers { get; set; }
        public virtual ICollection<License> Licenses { get; set; }
        public virtual ICollection<Monitor> Monitors { get; set; }
    }
}
